// Code generated by Fern. DO NOT EDIT.

package scheduledcheckout

import (
	context "context"

	schematichq "github.com/schematichq/schematic-go"
	core "github.com/schematichq/schematic-go/core"
	internal "github.com/schematichq/schematic-go/internal"
	option "github.com/schematichq/schematic-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &schematichq.ListScheduledCheckoutsRequest{
//	    CompanyID: schematichq.String(
//	        "company_id",
//	    ),
//	    Status: schematichq.ScheduledCheckoutStatusCancelled.Ptr(),
//	    Limit: schematichq.Int64(
//	        int64(1000000),
//	    ),
//	    Offset: schematichq.Int64(
//	        int64(1000000),
//	    ),
//	}
//	client.Scheduledcheckout.ListScheduledCheckouts(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListScheduledCheckouts(
	ctx context.Context,
	request *schematichq.ListScheduledCheckoutsRequest,
	opts ...option.RequestOption,
) (*schematichq.ListScheduledCheckoutsResponse, error) {
	response, err := c.WithRawResponse.ListScheduledCheckouts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &schematichq.CreateScheduledCheckoutRequest{
//	    CompanyID: "company_id",
//	    ExecuteAfter: schematichq.MustParseDateTime(
//	        "2024-01-15T09:30:00Z",
//	    ),
//	    FromPlanID: "from_plan_id",
//	    ToPlanID: "to_plan_id",
//	}
//	client.Scheduledcheckout.CreateScheduledCheckout(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateScheduledCheckout(
	ctx context.Context,
	request *schematichq.CreateScheduledCheckoutRequest,
	opts ...option.RequestOption,
) (*schematichq.CreateScheduledCheckoutResponse, error) {
	response, err := c.WithRawResponse.CreateScheduledCheckout(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Scheduledcheckout.GetScheduledCheckout(
//	    context.TODO(),
//	    "scheduled_checkout_id",
//	)
func (c *Client) GetScheduledCheckout(
	ctx context.Context,
	// scheduled_checkout_id
	scheduledCheckoutID string,
	opts ...option.RequestOption,
) (*schematichq.GetScheduledCheckoutResponse, error) {
	response, err := c.WithRawResponse.GetScheduledCheckout(
		ctx,
		scheduledCheckoutID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &schematichq.UpdateScheduledCheckoutRequest{}
//	client.Scheduledcheckout.UpdateScheduledCheckout(
//	    context.TODO(),
//	    "scheduled_checkout_id",
//	    request,
//	)
func (c *Client) UpdateScheduledCheckout(
	ctx context.Context,
	// scheduled_checkout_id
	scheduledCheckoutID string,
	request *schematichq.UpdateScheduledCheckoutRequest,
	opts ...option.RequestOption,
) (*schematichq.UpdateScheduledCheckoutResponse, error) {
	response, err := c.WithRawResponse.UpdateScheduledCheckout(
		ctx,
		scheduledCheckoutID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
