generatorName: go
inputSpec: https://schematic-openapi-da6da39.s3.amazonaws.com/latest.yml
templateDir: templates
outputDir: api
enablePostProcessFile: true
additionalProperties:
  generateInterfaces: true
  goImportAlias: schematicapi
  httpUserAgent: schematic-go@1.0.0
  isGoSubmodule: true
  packageName: api
  packageVersion: 1.0.0
  withGoMod: false
gitHost: github.com
gitUserId: SchematicHQ
gitRepoId: schematic-go
