generatorName: go
inputSpec: https://schematic-openapi-da6da39.s3.amazonaws.com/latest.yml
templateDir: templates
outputDir: api
additionalProperties:
  goImportAlias: schematicapi
  isGoSubmodule: true
  packageName: api
  packageVersion: 1.0.0
  withGoMod: false
gitHost: github.com
gitUserId: schematichq
gitRepoId: schematic-go
