// Code generated by Fern. DO NOT EDIT.

package planmigrations

import (
	context "context"
	schematichq "github.com/schematichq/schematic-go"
	core "github.com/schematichq/schematic-go/core"
	internal "github.com/schematichq/schematic-go/internal"
	option "github.com/schematichq/schematic-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListCompanyMigrations(
	ctx context.Context,
	request *schematichq.ListCompanyMigrationsRequest,
	opts ...option.RequestOption,
) (*schematichq.ListCompanyMigrationsResponse, error) {
	response, err := c.WithRawResponse.ListCompanyMigrations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CountCompanyMigrations(
	ctx context.Context,
	request *schematichq.CountCompanyMigrationsRequest,
	opts ...option.RequestOption,
) (*schematichq.CountCompanyMigrationsResponse, error) {
	response, err := c.WithRawResponse.CountCompanyMigrations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListMigrations(
	ctx context.Context,
	request *schematichq.ListMigrationsRequest,
	opts ...option.RequestOption,
) (*schematichq.ListMigrationsResponse, error) {
	response, err := c.WithRawResponse.ListMigrations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetMigration(
	ctx context.Context,
	// plan_version_migration_id
	planVersionMigrationID string,
	opts ...option.RequestOption,
) (*schematichq.GetMigrationResponse, error) {
	response, err := c.WithRawResponse.GetMigration(
		ctx,
		planVersionMigrationID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CountMigrations(
	ctx context.Context,
	request *schematichq.CountMigrationsRequest,
	opts ...option.RequestOption,
) (*schematichq.CountMigrationsResponse, error) {
	response, err := c.WithRawResponse.CountMigrations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
