// Code generated by Fern. DO NOT EDIT.

package licenses

import (
	context "context"

	schematichq "github.com/schematichq/schematic-go"
	core "github.com/schematichq/schematic-go/core"
	internal "github.com/schematichq/schematic-go/internal"
	option "github.com/schematichq/schematic-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &schematichq.ListLicensesRequest{
//	    FeatureIDs: []*string{
//	        schematichq.String(
//	            "feature_ids",
//	        ),
//	    },
//	    IDs: []*string{
//	        schematichq.String(
//	            "ids",
//	        ),
//	    },
//	    Name: schematichq.String(
//	        "name",
//	    ),
//	    Limit: schematichq.Int64(
//	        int64(1000000),
//	    ),
//	    Offset: schematichq.Int64(
//	        int64(1000000),
//	    ),
//	}
//	client.Licenses.ListLicenses(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListLicenses(
	ctx context.Context,
	request *schematichq.ListLicensesRequest,
	opts ...option.RequestOption,
) (*schematichq.ListLicensesResponse, error) {
	response, err := c.WithRawResponse.ListLicenses(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Licenses.GetSingleLicense(
//	    context.TODO(),
//	    "license_id",
//	)
func (c *Client) GetSingleLicense(
	ctx context.Context,
	// license_id
	licenseID string,
	opts ...option.RequestOption,
) (*schematichq.GetSingleLicenseResponse, error) {
	response, err := c.WithRawResponse.GetSingleLicense(
		ctx,
		licenseID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &schematichq.CountLicensesRequest{
//	    FeatureIDs: []*string{
//	        schematichq.String(
//	            "feature_ids",
//	        ),
//	    },
//	    IDs: []*string{
//	        schematichq.String(
//	            "ids",
//	        ),
//	    },
//	    Name: schematichq.String(
//	        "name",
//	    ),
//	    Limit: schematichq.Int64(
//	        int64(1000000),
//	    ),
//	    Offset: schematichq.Int64(
//	        int64(1000000),
//	    ),
//	}
//	client.Licenses.CountLicenses(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CountLicenses(
	ctx context.Context,
	request *schematichq.CountLicensesRequest,
	opts ...option.RequestOption,
) (*schematichq.CountLicensesResponse, error) {
	response, err := c.WithRawResponse.CountLicenses(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
