/*
Schematic API

Schematic API

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListAudienceUsersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAudienceUsersResponse{}

// ListAudienceUsersResponse struct for ListAudienceUsersResponse
type ListAudienceUsersResponse struct {
	// The returned resources
	Data []UserDetailResponseData `json:"data"`
	// Input parameters
	Params map[string]interface{} `json:"params"`
}

type _ListAudienceUsersResponse ListAudienceUsersResponse

// NewListAudienceUsersResponse instantiates a new ListAudienceUsersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAudienceUsersResponse(data []UserDetailResponseData, params map[string]interface{}) *ListAudienceUsersResponse {
	this := ListAudienceUsersResponse{}
	this.Data = data
	this.Params = params
	return &this
}

// NewListAudienceUsersResponseWithDefaults instantiates a new ListAudienceUsersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAudienceUsersResponseWithDefaults() *ListAudienceUsersResponse {
	this := ListAudienceUsersResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListAudienceUsersResponse) GetData() []UserDetailResponseData {
	if o == nil {
		var ret []UserDetailResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListAudienceUsersResponse) GetDataOk() ([]UserDetailResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListAudienceUsersResponse) SetData(v []UserDetailResponseData) {
	o.Data = v
}

// GetParams returns the Params field value
func (o *ListAudienceUsersResponse) GetParams() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *ListAudienceUsersResponse) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// SetParams sets field value
func (o *ListAudienceUsersResponse) SetParams(v map[string]interface{}) {
	o.Params = v
}

func (o ListAudienceUsersResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAudienceUsersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["params"] = o.Params
	return toSerialize, nil
}

func (o *ListAudienceUsersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAudienceUsersResponse := _ListAudienceUsersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAudienceUsersResponse)

	if err != nil {
		return err
	}

	*o = ListAudienceUsersResponse(varListAudienceUsersResponse)

	return err
}

type NullableListAudienceUsersResponse struct {
	value *ListAudienceUsersResponse
	isSet bool
}

func (v NullableListAudienceUsersResponse) Get() *ListAudienceUsersResponse {
	return v.value
}

func (v *NullableListAudienceUsersResponse) Set(val *ListAudienceUsersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAudienceUsersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAudienceUsersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAudienceUsersResponse(val *ListAudienceUsersResponse) *NullableListAudienceUsersResponse {
	return &NullableListAudienceUsersResponse{value: val, isSet: true}
}

func (v NullableListAudienceUsersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAudienceUsersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
