name: ci

on: [push]

jobs:
  compile:
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Compile
        run: go build ./...
  test:
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Test
        run: go test ./...
